version: '3.7'

services:
  # 1. Redpanda
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start --smp 2 --memory 4G
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"

  # 2. Redpanda Console (모니터링)
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda

  # 3. Spark(Master)
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/credentials/gcp-key.json
    command: [
      "/opt/spark/bin/spark-class",
      "org.apache.spark.deploy.master.Master"
    ]
    volumes:
      - ./scripts/consumer.py:/opt/spark/scripts/consumer.py:ro
      - ./scripts/dummy_init.py:/opt/spark/scripts/dummy_init.py:ro
      - ./config.yaml:/opt/spark/scripts/config.yaml:ro
      - ./spark_cache:/tmp/.ivy2
      - ./credentials:/opt/spark/credentials:ro

  # 4. Spark(Worker)
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    environment:
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_CORES=4
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/spark/credentials/gcp-key.json
    depends_on:
      - spark-master
    command: [
      "/opt/spark/bin/spark-class",
      "org.apache.spark.deploy.worker.Worker",
      "spark://spark-master:7077"
    ]
    volumes:
      - ./scripts/consumer.py:/opt/spark/scripts/consumer.py:ro
      - ./scripts/dummy_init.py:/opt/spark/scripts/dummy_init.py:ro
      - ./config.yaml:/opt/spark/scripts/config.yaml:ro
      - ./spark_cache:/tmp/.ivy2
      - ./credentials:/opt/spark/credentials:ro
